# Create database and tables for mango farm
CREATE DATABASE IF NOT EXISTS mango_farm;
USE mango_farm;

CREATE TABLE IF NOT EXISTS ratings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  product_id INT NOT NULL,
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(64) PRIMARY KEY,
  cart_json JSON NOT NULL,
  user_json JSON NOT NULL,
  amount INT NOT NULL,
  payment_method VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  phone VARCHAR(20) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  email VARCHAR(128) NULL,
  address TEXT NULL,
  city VARCHAR(64) NULL,
  state VARCHAR(64) NULL,
  pincode VARCHAR(12) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
